name: CI/CD

on:
  push:
    branches:
    - master
    paths-ignore:
    - 'README.md'
    - 'LICENSE'
    - 'CODE_OF_CONDUCT.md'
  pull_request:
    branches:
    - master
    paths-ignore:
    - 'README.md'
    - 'LICENSE'
    - 'CODE_OF_CONDUCT.md'
jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    container:
      image: ruby:2.7.1-buster
    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: bundle install
    - name: Run Tests
      run: bundle exec rspec
